### ISSUE TITLE
Instructors need a page where they see all forums for a course

### ISSUE THREAD

**Issue by sampaccoud** [openfun/ashley#232]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
When a course has many forums (up to 100 in some courses in production), the instructor does not have a view to see all the forums. 
On the course on which the forums were created, clicking on the "home" button shows all the forums for the course.
However, when the course has been copied, clicking on the "home" button does not show them anymore.

**Describe the solution you'd like**
Make sure all forum for a course are listed on the "home" page.

**Describe alternatives you've considered**
After understanding what the difference is between the original course and its copies, we can decide if the "home" page can be fixed or if a new page must be added.

**Comment by carofun** [comment]
Normal behaviour without copy

https://user-images.githubusercontent.com/76939263/148103020-b72d2985-695e-43d8-9469-bb4a03b2eff1.mov

**Comment by sampaccoud** [comment]
Seeing your video, I think that people are also conditioned to not click so much on breadcrumbs... 
@cuchulainn-fun So maybe this was the problem and we need a way to access this view that is more obvious?

**Comment by cuchulainn-fun** [comment]
@sampaccoud I think in depends on the use case, because in my point of view the behavior between ashley forum and the edx forum is quite similar on click number, 2 clicks. (cf.gif an attach)

**Use case** : 
- if the forum has direct access via the horizontal menu, it amounts to 2 clicks to have the view which brings together all the forums inserted in the course. So normally people shouldn't be confused
- On the other hand, if the forum is not at the level of the horizontal menu, the number of clicks increases. There are between 3 and 4 clicks in total, depending on where the teachers have placed the forum in the course (cf. gif example with 3 clicks attached)

In any case, if it's possible to set up a way to access this view more obviously, that's a good thing.

![overview-forum-in-edx](https://user-images.githubusercontent.com/92527905/148350903-cf81eec1-22be-4853-bf4a-e73c78af606c.gif)
![ashley-navigation-access-overview-forum_course](https://user-images.githubusercontent.com/92527905/148352777-61bdf3ec-09cf-4608-98b1-b4ad49736d68.gif)
